name: 'Pet Action'
description: 'Sync epics with subtasks using parent-child links. Inspired from https://github.com/ribtoks/parent-issue-update '
inputs:
  TOKEN:
    description: "Github token"
    default: ""
runs:
  using: 'node12'
  main: 'dist/index.js'